[package]
name = "pickup-rust"
version = "0.1.0"
authors = ["Andy O'Neill <andy@potatoriot.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "^3"
env_logger = "^0"
log = "^0"
rodio = "^0"

