name: Go CI

on:
  push:
    branches: [$default-branch]
  pull_request:
    paths-ignore:
      - rs/**

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: linux
            arch: arm
            arm: 5
          - os: linux
            arch: arm
            arm: 7
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
      fail-fast: false

    runs-on: ubuntu-latest
    name: Build

    defaults:
      run:
        shell: bash
        working-directory: ./go

    steps:
      - uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24.x
          cache-dependency-path: go/frontend/yarn.lock
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: 1.27
          cache-dependency-path: go/go.sum
      # We don't have it setup in the Makefile to avoid double-building, but 'make lint'
      # requires the react build to have completed.
      - run: make frontend

      - run: make lint

      - name: Go build
        run: go build -o pickup
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          GOARM: ${{ matrix.arm }}
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v7
        with:
          name: pickup_${{ matrix.os }}_${{ matrix.arch }}${{ matrix.arm}}
          path: go/pickup
          if-no-files-found: error

