name: Go CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./go


    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
    # We don't have it setup in the Makefile to avoid double-building, but 'make lint'
    # requires the react build to have completed.
    - run: make frontend

    - run: make lint

    - name: Go build (Linux, AMD64)
      run: go build -o pickup.$GOOS.$GOARCH
      env:
        GOOS: linux
        GOARCH: amd64
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: pickup (Linux, AMD64)
        path: pickup.linux.amd64

    - name: Go build (Linux, ARM5)
      run: go build -o pickup.$GOOS.$GOARCH$GOARM
      env:
        GOOS: linux
        GOARCH: arm
        GOARM: 5
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: pickup (Linux, ARM5)
        path: pickup.linux.arm5

    - name: Go build (Darwin, ARM5)
      run: go build -o pickup.$GOOS.$GOARCH
      env:
        GOOS: darwin
        GOARCH: amd64
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: pickup (Darwin, AMD64)
        path: pickup.darwin.amd64

