name: Rust CI

on: push

defaults:
  run:
    shell: bash
    working-directory: rs

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: install libraries
        run: sudo apt-get install libasound2-dev pulseaudio
      # Plain ALSA fails in CI since there's no real device.
      # I copied the pulseaudio trick from pulseaudio-rs CI config.
      # https://github.com/colinmarc/pulseaudio-rs/blob/main/.github/workflows/tests.yaml
      - name: Setup pulseaudio
        run: |
          systemctl --user enable pulseaudio
          systemctl --user start pulseaudio
          pactl load-module module-null-sink sink_name=test_sink
          pactl set-default-sink test_sink
      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            rs/target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
      - name: Update rust toolchain
        run: |
          rustup update
          rustup component add clippy
      - name: "Check format"
        run: cargo fmt -- --check
      - name: "Run clippy linter"
        run: cargo clippy --no-deps -- -Dwarnings
      - name: "Run tests"
        run: cargo test
